### PR TITLE
Added IsAllowed and DoNotDuplicate check.

### PR DESCRIPTION
**Pull request by Grocel**
It should be able to fix https://github.com/wiremod/advduplicator/issues/65 and https://github.com/wiremod/advduplicator/issues/64

This is analog to: https://github.com/wiremod/advdupe2/pull/51

### CODE REVIEW

**Comment by TomyLobo** [comment]
uh, can't they just make a applydupeinfo hook to disintegrate the entity on paste?

**Comment by Divran** [comment]
Yes but that's not a clean solution

**Comment by Grocel** [comment]
@Divran: Do you mean that pull request or TomyLobo's solution?

@TomyLobo: The problem with deleting the entity on paste, that it would be too late already in some cases. This pull request was made to add the same filter features as Garry's duplicator has and to fix the linked bugs.

**Comment by Divran** [comment]
>@Divran: Do you mean that pull request or TomyLobo's solution?

I meant tomylobo's

**Comment by Nebual** [comment]
Seems like a good idea, I say merge it.

**Comment by Divran** [comment]
Yeah fine by me

**Comment by TomyLobo** [comment]
If that's Garry's interface and we should be implementing it, so fine by me.

**Comment by Grocel** [comment]
OK, it's nice to hear that everything is seeming fine to merge. Is there anything left to clear?

**Comment by TomyLobo** [comment]
All except this one:
https://github.com/Grocel/advduplicator/blob/master/lua/autorun/server/advdupe.lua#L716-L720
We can't have "do not steal" in an open source project
also, typo in "compatable"

**Comment by Divran** [comment]
>All except this one:
https://github.com/Grocel/advduplicator/blob/master/lua/autorun/server/advdupe.lua#L716-L720
We can't have "do not steal" in an open source project

uh how long has that been there? It doesn't look like grocel's patch added that

**Comment by TomyLobo** [comment]
That is correct, however, it's still there and needs to go :)

**Comment by Grocel** [comment]
Thanks for merging.

Well, I wouldn't add such a thing to a pull request. I guess you can remove it yourself. :)

Also it seems you haven't noticed the [patch for the Adv Dupe 2](https://github.com/wiremod/advdupe2/pull/51) in the OP yet. Can you check that out too?

**Pull request merged**
